### ISSUE TITLE
Cannot set property 'body' of undefined

### ISSUE THREAD

**Issue by nod33** [christophebe/crawler.ninja#3]
Sorry it appears that I didn't fixed this properly in my last pull request :(

/node_modules/crawler-ninja/lib/http/http-request.js:126
          result.body='';
                     ^

TypeError: Cannot set property 'body' of undefined
    at onContent (/node_modules/crawler-ninja/lib/http/http-request.js:126:22)
    at /node_modules/crawler-ninja/lib/http/http-request.js:97:30
    at Gunzip.onError (zlib.js:212:5)
    at emitOne (events.js:77:13)
    at Gunzip.emit (events.js:169:7)
    at Zlib._handle.onerror (zlib.js:366:10)

**Comment by christophebe** [comment]
Can you give me  the url that you crawl in order to check this error ? 
Thanks
